### ISSUE TITLE
Shrink download icon on some devices.

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/infopage#2]
On my phone it looks well but the download icon is to large on big devices.

**Comment by hendriku** [comment]
Same with the get it on google play icon!

**Comment by MalteBartels** [comment]
I fixed the responsiveness of the Download Icon. It behaves like all images now. However, this means it is big on all devices. I like that. We could discuss choosing something totally different, like a screenshot from the Playstore.

The Google Play Icon's size is predefined, it should not be changed.

**Comment by hendriku** [comment]
Nice!
