### ISSUE TITLE
Beta tester play store connection

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/infopage#4]
Currently it says you have to write an email to test the beta. This is wrong, link the playstore beta program

**Comment by MalteBartels** [comment]
![bildschirmfoto 2017-10-14 um 09 58 17](https://user-images.githubusercontent.com/28776631/31573994-59c9d4b6-b0c6-11e7-9911-aea642b15ec0.png)

I added the information. How do you like it?

**Comment by hendriku** [comment]
Great, let's use this.
